name: dataset
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SUN'


jobs:
  dataset:
    timeout-minutes: 15 # if it takes more than 2 minutes, there's a network error.
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go run . dump -C contests/computational.json out/computational.json
      - run: go run . dump -C contests/international.json out/international.json
      - run: go run . dump -C contests/nationaloly.json out/nationaloly.json
      - name: Delete nightly release
        run: gh release delete dataset --yes || true
      - name: Upload to releases
        run: |
          gh release create dataset --prerelease --title "Search.MAATester.com Dataset" --target $GITHUB_SHA out/*
